; PlatformIO Project Configuration — MeteoStationPrototype (MSP1)
; Carte : ESP32 (esp32dev). Station meteo + tracker solaire.

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_extra_dirs = ../shared
build_flags = -I../ -include "soc/gpio_struct.h"
extra_scripts = pre:scripts/upload_hook_otadata.py

lib_deps =
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	adafruit/Adafruit Unified Sensor
	adafruit/DHT sensor library
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SSD1306
	adafruit/Adafruit BusIO
	paulstoffregen/OneWire
	milesburton/DallasTemperature
	madhephaestus/ESP32Servo
	fbiego/ESP32Time
	arduino-libraries/Arduino_JSON
	mobizt/ESP Mail Client

lib_ignore = WebServer

[env:esp32dev_test]
extends = env:esp32dev
build_flags = -I../ -include "soc/gpio_struct.h" -DTEST_MODE
