; PlatformIO Project Configuration — N3PhasmesProto (N3PP)
; Carte : ESP32 (esp32dev). Serre / aquaponie.

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = ../config/partitions/min_spiffs.csv
lib_extra_dirs = ../shared
build_flags = -I../
extra_scripts = pre:scripts/upload_hook_otadata.py

lib_deps =
	bblanchon/ArduinoJson@7.4.3
	ESP32Async/AsyncTCP@3.4.10
	ESP32Async/ESPAsyncWebServer@3.10.0
	adafruit/Adafruit Unified Sensor@1.1.15
	adafruit/DHT sensor library@1.4.7
	adafruit/Adafruit GFX Library@1.12.5
	adafruit/Adafruit SSD1306@2.5.16
	adafruit/Adafruit BusIO@1.17.4
	fbiego/ESP32Time@2.0.6
	arduino-libraries/Arduino_JSON@0.2.0
	mobizt/ESP Mail Client@3.4.24

lib_ignore = WebServer

[env:esp32dev_test]
extends = env:esp32dev
build_flags = -I../ -DTEST_MODE
